# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

use_frameworks!

workspace 'SimpleCounter.xcworkspace'

target 'SimpleCounterApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for TestFramework
  
  project './SimpleCounterApp/SimpleCounterApp.xcodeproj'
  pod 'UICircularProgressRing', '6.1.0'

end

target 'SimpleCounterFramework' do
    project './SimpleCounterFramework/SimpleCounterFramework.xcodeproj'
    pod 'UICircularProgressRing', '6.1.0'
end
