# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'AFNetworkingTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AFNetworkingTest

  pod 'AFNetworking', '~> 3.0'

  target 'AFNetworkingTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AFNetworkingTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
