# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseProject

  # 网络请求
  pod 'Moya', '~> 13.0'
  pod 'Alamofire'
  
  pod 'SwiftyJSON', '~> 4.0'
  
  # MD5
  pod 'SwiftHash'


end
