use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'Combinestagram' do
    pod 'RxSwift'
    pod 'RxCocoa'
end
